Repository Jim-Hodapp-Coaching/esp32-wroom-rp, pull requests merged in 2022-09, with the labels that each got.

#22 Join a provided wifi network
  Cargo.toml
  examples/join.rs
  src/lib.rs
  src/protocol.rs
  src/spi.rs
Labels: feature work

#25 Leave a previously joined WiFi network
  examples/join.rs
  src/lib.rs
  src/protocol.rs
  src/spi.rs
Labels: feature work

#26 Adds examples/secrets.rs
  examples/join.rs
  examples/secrets/secrets.rs
Labels: enhancement

#28 Restructure project layout so unit and host tests work
  .gitignore
  Cargo.toml
  README.md
  cross/.cargo/config
  cross/Cargo.toml
  cross/build.rs
  cross/get_fw_version/Cargo.toml
  cross/get_fw_version/src/main.rs
  cross/get_fw_version/src/secrets/secrets.rs
  cross/join/Cargo.toml
  cross/join/src/main.rs
  cross/join/src/secrets/secrets.rs
  cross/memory.x
  esp32-wroom-rp/Cargo.toml
  esp32-wroom-rp/src/gpio.rs
  esp32-wroom-rp/src/lib.rs
  esp32-wroom-rp/src/protocol.rs
  esp32-wroom-rp/src/spi.rs
  esp32-wroom-rp/src/wifi.rs
  host-tests/Cargo.toml
  host-tests/tests/spi.rs
  tests/lib.rs
Labels: enhancement, project structure

#29 Improve NINA protocol function architecture 2
  cross/join/src/main.rs
  esp32-wroom-rp/src/protocol.rs
  esp32-wroom-rp/src/protocol/operation.rs
  esp32-wroom-rp/src/spi.rs
Labels: enhancement

#31 Eliminates all current rustc compile warnings
  cross/get_fw_version/src/main.rs
  cross/join/src/main.rs
  esp32-wroom-rp/src/gpio.rs
  esp32-wroom-rp/src/lib.rs
  esp32-wroom-rp/src/protocol.rs
  esp32-wroom-rp/src/protocol/operation.rs
  esp32-wroom-rp/src/spi.rs
  host-tests/tests/spi.rs
Labels: enhancement

#32 fix number_of_params issue
  esp32-wroom-rp/src/spi.rs
Labels: bug
