Repository Jim-Hodapp-Coaching/esp32-wroom-rp, pull requests merged in 2022-11, with the labels that each got.

#37 Add GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: project structure

#44 Address all known static analysis security issues and Clippy warnings
  cross/get_fw_version/Cargo.toml
  cross/get_fw_version/src/main.rs
  cross/join/Cargo.toml
  cross/join/src/main.rs
  esp32-wroom-rp/Cargo.toml
  esp32-wroom-rp/src/gpio.rs
  esp32-wroom-rp/src/lib.rs
  esp32-wroom-rp/src/protocol.rs
  esp32-wroom-rp/src/protocol/operation.rs
  esp32-wroom-rp/src/spi.rs
Labels: bug

#45 Support DNS
  cross/Cargo.toml
  cross/dns/Cargo.toml
  cross/dns/src/main.rs
  cross/dns/src/secrets/secrets.rs
  esp32-wroom-rp/src/lib.rs
  esp32-wroom-rp/src/network.rs
  esp32-wroom-rp/src/protocol.rs
  esp32-wroom-rp/src/spi.rs
Labels: feature work
