Repository Jim-Hodapp-Coaching/esp32-wroom-rp, pull requests merged in 2023-01, with the labels that each got.

#58 Clean up imports
  esp32-wroom-rp/src/lib.rs
  esp32-wroom-rp/src/protocol.rs
  esp32-wroom-rp/src/protocol/operation.rs
  esp32-wroom-rp/src/spi.rs
  esp32-wroom-rp/src/tcp_client.rs
  esp32-wroom-rp/src/wifi.rs
Labels: project structure

#59 Mature documentation and ready for publishing to crates.io
  cross/get_fw_version/src/main.rs
  esp32-wroom-rp/src/gpio.rs
  esp32-wroom-rp/src/lib.rs
  esp32-wroom-rp/src/network.rs
  esp32-wroom-rp/src/protocol.rs
  esp32-wroom-rp/src/spi.rs
  esp32-wroom-rp/src/tcp_client.rs
  esp32-wroom-rp/src/wifi.rs
Labels: documentation, project structure

#68 Update Cargo.toml for 0.3.0 release
  CHANGELOG.md
  esp32-wroom-rp/Cargo.toml
Labels: release

#69 Copy README to crate level to satisfy crates.io publish
  cross/dns/Cargo.toml
  cross/get_fw_version/Cargo.toml
  cross/join/Cargo.toml
  cross/send_data_tcp/Cargo.toml
  esp32-wroom-rp/Cargo.toml
  esp32-wroom-rp/README.md
  host-tests/Cargo.toml
Labels: release
